---
title: "Make an interactive map of focal trees"
author: "Eleanor Jackson"
date: '`r format(Sys.time(), "%d %B, %Y")`'
always_allow_html: true
output: 
  github_document:
    keep_html: true
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.path = "figures/2021-05-28_create-map/")
```

```{r packages}
library("tidyverse")
library("sp")
library("ggmap")
library("geojsonio")
library("leaflet")
```

## Read in gpx file and clean up

```{r read-gpx}
plotKML::readGPX(here::here("data", "raw", "waypoints.gpx")) %>%
  map_df(~.) %>%
  rename(id = name) %>%
  mutate(taxa = case_when(sym == "Park" ~ "Prunus_spinosa",
                          sym == "Flag, Blue" ~ "Crataegus_laevigata")) -> waypoints
```

## Make a static map

```{r ggmap}
bbox <- make_bbox(c(min(waypoints$lon), max(waypoints$lon)), 
                  c(min(waypoints$lat), max(waypoints$lat)))

ggmap(get_map(bbox, source = "osm", messaging = FALSE)) +
  geom_point(data = waypoints, 
           aes(lon, lat, colour = taxa))

# not very detailed
```

```{r make-sp}
# make the data a spatial df object 
SpatialPointsDataFrame(coords = select(waypoints, lon, lat), 
                       data = waypoints, 
                       proj4string = CRS("+init=epsg:4326")) -> waypoints_sp
```

## Make an interactive map

```{r leaflet-map}
# colours
pal <- colorFactor(c("navy", "red"), c("Prunus_spinosa", "Crataegus_laevigata"))

# make a map with leaflet
leaflet(data = waypoints_sp)%>% 
  addCircleMarkers(label = ~id, color = ~pal(taxa), 
                            fillOpacity = 0.8, stroke = FALSE, radius = 5) %>% 
  addTiles() %>%
  addLegend(pal = pal, values = ~taxa)

# export sp object as geojson
waypoints_geojson <- geojson_json(waypoints_sp)
geojson_write(waypoints_geojson, file = "focal-trees-map.geojson")
```

[View the interactive version here](focal-trees-map.geojson)
