---
title: "First look at mapping data"
author: "Eleanor Jackson"
date: '`r format(Sys.time(), "%d %B, %Y")`'
always_allow_html: true
output: 
  github_document:
    keep_html: true
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.path = "figures/2022-07-07_explore-mapping-data/")
source(here::here("code", "secrets.R"))
```

We want to conduct herbivory surveys on individuals at high and low conspecific densities. To identify them we'll need a measure of connectivity. I'm going to take a first look at the mapping data that has been collected so far and have a go at calculating connectivity for all of the trees.

```{r packages}
library("tidyverse")
library("janitor")
library("googledrive")
library("here")
```

## Cleaning

```{r clean}
googledrive::drive_auth(email = "eleanor.elizabeth.j@gmail.com",
                        scopes = "https://www.googleapis.com/auth/drive") 

files <- drive_ls(GDRIVE_FOLDER_URL,
                  pattern = "^[0-9]{2}.csv")

files  %>%
  mutate(id = sprintf("https://docs.google.com/uc?id=%s&export=download", id)) %>%
  pull(id) -> urls

names(urls) <- pull(files, name)

data_list <- lapply(urls, read.csv, na.strings = c("","NA"))

repair_col_names <- function (plot) {
  plot %>%
    rename_with(recode, "DBH" = "BHD") %>%
    mutate(BHD = ifelse("BHD" %in% names(.), BHD, NA),
           BHC = ifelse("BHC" %in% names(.), BHC, NA),
           Other.HC = ifelse("Other.HC" %in% names(.), Other.HC, NA)) %>% 
    mutate(across(c(BHD, BHC, Other.HC, Other.HD), as.numeric)) %>%
    mutate(Notes = as.character(Notes)) %>%
    select(-contains("X"))
}

data_list_col_repair <- lapply(data_list, repair_col_names)

repair_tree_names <- function (plot, plot_name) {
  plot %>%
    mutate(Name = replace(Name, pluck(1, 1), 
                          paste0("focal_", readr::parse_number(plot_name)))) %>%
    mutate(Name = gsub("h", "", x = Name, ignore.case = TRUE)) %>%
    mutate(Name = sub("^0+", "", Name) ) %>%
    mutate(Name = as.factor(Name))
}

data_list_name_repair <- imap(data_list_col_repair, repair_tree_names)

all_plots <- bind_rows(data_list_name_repair, .id = "plot")

all_plots %>%
  clean_names() %>%
  remove_empty("rows") %>% 
  fill(c("name", "longitude", "latitude", "solution_status", 
         "cs_name", "form", "reproductive")) -> clean_plots

```

