---
title: "Beetle sampling data"
author: '`r Sys.getenv("USER")`'
date: '`r format(Sys.time(), "%d %B, %Y")`' 
always_allow_html: true
output: 
  github_document:
    keep_html: true
---
	
```{r setup, include = FALSE}
file_name <- rstudioapi::getSourceEditorContext()$path

knitr::opts_chunk$set(
  fig.path =
    paste0("figures/", sub("\\.Rmd$", "", basename(file_name)), "/", sep = "")
)

ggplot2::theme_set(ggplot2::theme_classic(base_size = 10))
```

Taking a very quick look at Susie's data.

```{r packages, message=FALSE, warning=FALSE}
library("tidyverse")
library("here")
library("janitor")
library("patchwork")
library("vegan")
```

```{r data}
read_csv(here::here("data", "raw", "beetle_sampling.csv")) %>% 
  clean_names() %>% 
  mutate(
    date = convert_to_date(date, character_fun = lubridate::dmy)
    ) -> pooled_data
```

```{r}
pooled_data %>% 
  uncount(n) -> unpooled_data
```

## Calculate Shannon diversity

```{r diversity}
unpooled_data %>% 
  filter(species_genus != "unknown") %>% 
  summarise(abundance = n(), .by = c(species_genus, tree_id)) %>% 
  pivot_wider(names_from = species_genus, values_from = abundance) %>% 
  column_to_rownames("tree_id") %>% 
  replace(is.na(.), 0) -> diversity_matrix_sp

diversity(diversity_matrix_sp) %>% 
  as_tibble(rownames = "tree_id") %>% 
  rename(species_diversity = value) -> diversity_sp

unpooled_data %>% 
  filter(family != "unknown") %>% 
  summarise(abundance = n(), .by = c(family, tree_id)) %>% 
  pivot_wider(names_from = family, values_from = abundance) %>% 
  column_to_rownames("tree_id") %>% 
  replace(is.na(.), 0) -> diversity_matrix_fam

diversity(diversity_matrix_fam) %>% 
  as_tibble(rownames = "tree_id") %>% 
  rename(family_diversity = value) -> diversity_fam

```

## Calculate richness

```{r richness}
unpooled_data %>% 
  filter(species_genus != "unknown") %>% 
  summarise(species_richness = n_distinct(species_genus), 
            .by = tree_id) -> rich_sp

unpooled_data %>% 
  filter(family != "unknown") %>% 
  summarise(family_richness = n_distinct(family), 
            .by = tree_id) -> rich_fam

```

## Combine with abundance

```{r}
unpooled_data %>% 
  filter(species_genus != "unknown") %>% 
  summarise(abundance = n(), .by = c(tree_id, flowering)) -> abund_data

abund_data %>% 
  left_join(rich_fam) %>% 
  left_join(rich_sp) %>%
  mutate(tree_id = as.character(tree_id)) %>% 
  left_join(diversity_fam) %>% 
  left_join(diversity_sp) %>%
  mutate(tree_id = as.numeric(tree_id)) -> indices
  
readRDS(here::here("data", "clean", "connectivity_data.rds")) %>% 
  select(plot, connectivity, repro_connectivity) %>% 
  full_join(indices, by = c("plot" = "tree_id"))  -> indices_con

readRDS(here::here("data", "clean", "hawthorn_plots.rds")) %>%
  filter(tree_id == "tree_0") %>%
  mutate(plot = as.numeric(plot)) %>%
  select(plot, dbh) %>% 
  full_join(indices_con, by = "plot") %>% 
  rename(tree_id = plot) %>% 
  drop_na(flowering) -> plotting_data
  
```


## Flowering vs non-flowering trees

```{r flowering-vs-nonflowering, echo=FALSE, fig.height=3, fig.width=8, message=FALSE, warning=FALSE}
plotting_data %>% 
  drop_na(flowering) %>% 
  ggplot(aes(y = abundance, x = flowering)) +
  geom_boxplot(outlier.colour = NA, width = .12)+
  ggdist::stat_dots(
    side = "left", justification = 1.1
  ) -> p_n_fl

plotting_data %>% 
  drop_na(flowering) %>% 
  ggplot(aes(y = species_richness, x = flowering)) +
  geom_boxplot(outlier.colour = NA, width = .12)+
  ggdist::stat_dots(
    side = "left", justification = 1.1
  )  -> p_sp_fl

plotting_data %>% 
  drop_na(flowering) %>% 
  ggplot(aes(y = species_diversity, x = flowering)) +
  geom_boxplot(outlier.colour = NA, width = .12)+
  ggdist::stat_dots(
    side = "left", justification = 1.2, scale = .5
  )  -> p_d_fl

p_n_fl + p_sp_fl + p_d_fl

```

## Connectivity and dbh

```{r connectivity, echo=FALSE, fig.height=8, fig.width=8, message=FALSE, warning=FALSE}
plotting_data %>%
  ggplot(aes(x = connectivity, y = abundance, 
             fill = flowering, colour = flowering)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_n_con

plotting_data %>%
  ggplot(aes(x = repro_connectivity, y = abundance, 
             fill = flowering, colour = flowering)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_n_rcon

plotting_data %>%
  ggplot(aes(x = connectivity, y = species_richness, 
             fill = flowering, colour = flowering)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_sp_con

plotting_data %>%
  ggplot(aes(x = repro_connectivity, y = species_richness, 
             fill = flowering, colour = flowering)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_sp_rcon

plotting_data %>%
  ggplot(aes(x = connectivity, y = species_diversity, 
             fill = flowering, colour = flowering)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_d_con

plotting_data %>%
  ggplot(aes(x = repro_connectivity, y = species_diversity, 
             fill = flowering, colour = flowering)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_d_rcon

plotting_data %>%
  ggplot(aes(x = dbh, y = abundance, 
             fill = flowering, colour = flowering)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_n_dbh


plotting_data %>%
  ggplot(aes(x = dbh, y = species_richness, 
             fill = flowering, colour = flowering)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_sp_dbh

plotting_data %>%
  ggplot(aes(x = dbh, y = species_diversity, 
             fill = flowering, colour = flowering)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_d_dbh

(p_n_con + p_sp_con +  p_d_con) / 
  (p_n_rcon + p_sp_rcon + p_d_rcon) / 
  (p_n_dbh + p_sp_dbh + p_d_dbh) + 
  plot_layout(guides = "collect") & theme(legend.position = 'bottom')

```

```{r}
glm(species_diversity ~ connectivity * dbh * flowering, data = plotting_data) %>% 
  summary()

glm(species_diversity ~ repro_connectivity * dbh * flowering, data = plotting_data) %>% 
  summary()
```


## Possible pollinators

Assuming that species only found on flowering trees are pollinators. 
Does this change any patterns?

```{r}
unpooled_data %>% 
  filter(species_genus != "unknown") %>% 
  filter(flowering == TRUE) %>% 
  distinct(species_genus) -> on_flowers

unpooled_data %>% 
  filter(species_genus != "unknown") %>% 
  filter(flowering == FALSE) %>% 
  distinct(species_genus) -> not_on_flowers

setdiff(on_flowers, not_on_flowers) -> poss_pollinators

unpooled_data %>% 
  filter(species_genus %in% poss_pollinators$species_genus) -> pollinator_data

```

```{r message=FALSE}
#richness
pollinator_data %>% 
  filter(species_genus != "unknown") %>% 
  summarise(species_richness = n_distinct(species_genus), .by = tree_id) -> rich_sp_pol

# abundance
pollinator_data %>% 
  filter(species_genus != "unknown") %>% 
  summarise(abundance = n(), .by = tree_id) -> abund_data_pol

#diversity
pollinator_data %>% 
  filter(species_genus != "unknown") %>% 
  summarise(abundance = n(), .by = c(species_genus, tree_id)) %>% 
  pivot_wider(names_from = species_genus, values_from = abundance) %>% 
  column_to_rownames("tree_id") %>% 
  replace(is.na(.), 0) -> diversity_matrix_sp_pol

diversity(diversity_matrix_sp) %>% 
  as_tibble(rownames = "tree_id") %>% 
  rename(species_diversity = value) -> diversity_sp_pol

plotting_data %>% 
  select(tree_id, dbh, connectivity, repro_connectivity, flowering) %>% 
  filter(flowering == TRUE) %>% 
  left_join(rich_sp_pol) %>% 
  left_join(abund_data_pol) %>% 
  mutate(tree_id = as.character(tree_id)) %>%
  left_join(diversity_sp_pol) -> plotting_data_pol

```


```{r poss-polinators-only, echo=FALSE, fig.height=8, fig.width=8, warning=FALSE, message=FALSE}
plotting_data_pol %>%
  ggplot(aes(x = connectivity, y = species_richness)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_sp_con_pol

plotting_data_pol %>% 
  ggplot(aes(x = repro_connectivity, y = species_richness)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_sp_rcon_pol

plotting_data_pol %>%
  ggplot(aes(x = connectivity, y = abundance)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_n_con_pol

plotting_data_pol %>%
  ggplot(aes(x = repro_connectivity, y = abundance)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_n_rcon_pol

plotting_data_pol %>%
  ggplot(aes(x = dbh, y = abundance)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_n_dbh_pol

plotting_data_pol %>%
  ggplot(aes(x = dbh, y = species_richness)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_sp_dbh_pol

plotting_data_pol %>%
  ggplot(aes(x = connectivity, y = species_diversity)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_d_con_pol

plotting_data_pol %>%
  ggplot(aes(x = repro_connectivity, y = species_diversity)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_d_rcon_pol

plotting_data_pol %>%
  ggplot(aes(x = dbh, y = species_diversity)) +
  geom_point() +
  geom_smooth(method = "lm") -> p_d_dbh_pol

(p_n_con_pol + p_sp_con_pol +  p_d_con_pol) / 
  (p_n_rcon_pol + p_sp_rcon_pol + p_d_rcon_pol) / 
  (p_n_dbh_pol + p_sp_dbh_pol + p_d_dbh_pol) +
  plot_annotation(title = "beetle species only found on flowering trees")
```

```{r}
glm(species_diversity ~ connectivity * dbh, data = plotting_data_pol) %>% 
  summary()

glm(species_diversity ~ repro_connectivity * dbh, data = plotting_data_pol) %>% 
  summary()
```
