---
title: "Make survey calendar figure"
author: '`r Sys.getenv("USER")`'
date: '`r format(Sys.time(), "%d %B, %Y")`' 
always_allow_html: true
output: 
  github_document:
    keep_html: true
---
	
```{r setup, include = FALSE}
file_name <- rstudioapi::getSourceEditorContext()$path

knitr::opts_chunk$set(
  fig.path =
    paste0("figures/", sub("\\.Rmd$", "", basename(file_name)), "/", sep = "")
)

ggplot2::theme_set(ggplot2::theme_classic(base_size = 10))
```

```{r packages, message=FALSE, warning=FALSE}
library("tidyverse")
library("here")
```

```{r}
tibble(
  month = rep(1:12, 3),
  year = factor(c(rep(2021, 12),
           rep(2022, 12),
           rep(2023, 12)))
) -> data
```

```{r}
ggplot(data, aes(x = as.factor(month), y = year, colour = year, group = year)) +
  geom_line() +
  coord_polar() 
```

```{r}
ggplot(data, aes(x = month, y = year, colour = year, group = year)) +
  geom_line() +
  coord_polar(start = -89.5) + 
  scale_x_continuous(expand = c(0, 0), limits = c(1,24), breaks = c(1:12)) 
```

```{r}
survey_dates <- tibble(
  year = factor(c(2022, 2022, 2023, 2023, 2021, 2021, 2023, 
                  2023, 2021, 2021, 2021, 2021)),
  month = factor(c(5, 6, 5, 6, 8, 9, 6, 9, 8, 12, 1, 3)),
  day = factor(c(9, 17, 31, 29, 5, 29, 26, 29, 5, 31, 1, 7)),
  type = factor(c("set", "set", "set", "set", "short_drop", 
                  "short_drop", "short_drop", "short_drop", 
                  "long_drop", "long_drop", "long_drop", "long_drop"))
) %>%
  mutate(date = as.Date(paste("2023", month, day, sep="-"),
                        format = "%Y-%m-%d"),
         type = paste(year, type)
                              )
```

```{r}
ggplot(survey_dates, aes(x = date, y = type, colour = year, group = type)) +
  geom_line() +
  coord_polar() +
  scale_x_date(date_breaks = "1 month",  expand = c(0,0),
               date_labels = "%B")
```


Trying `geom_segment` rather than `geom_line`:

```{r}
survey_segs <- tibble(
  year = factor(c(2022, 2023, 2023, 2021, 2021, 2020)),
  start = as.Date(c("2023-05-09", "2023-05-31", "2023-06-26", "2023-08-05", 
                    "2023-01-01", "2023-01-01"), format = "%Y-%m-%d"),
  end = as.Date(c("2023-06-17", "2023-06-29", "2023-09-29", "2023-12-31", 
                  "2023-03-07", "2023-01-01"), format = "%Y-%m-%d"),
  type = factor(c("2022set", "2023set", "2023short_drop", "2021long_drop", 
                  "2021long_drop", "2020spare"))
)
```

```{r}
ggplot(survey_segs, 
       aes(x = start, xend = end, y = type, yend = type, 
           colour = year, group = year)) +
  geom_segment() 
```

```{r}
ggplot(survey_segs, 
       aes(x = start, xend = end, y = type, yend = type, 
           colour = year, group = year)) +
  geom_segment(linewidth = 2, lineend = "round") +
  coord_polar(start = -89.5) +
  scale_x_date(date_breaks = "1 month",  expand = c(0,0),
               date_labels = "%b",
               limits = as.Date(c("2023-01-01", "2024-12-31"))) 
```

```{r}
survey_segs_2 <- tibble(
  year = factor(c(2022, 2023, 2021)),
  start = as.Date(c("2023-05-09", "2023-05-31", "2023-08-05" 
                    ), format = "%Y-%m-%d"),
  end = as.Date(c("2023-06-17", "2023-09-29", 
                  "2024-03-07"), format = "%Y-%m-%d"),
  type = c(13, 14, 12))
```


```{r}
pal <- viridisLite::viridis(n = 3, begin = 0.2, end = 0.8, option = "mako")
names(pal) <- c("2021", "2022", "2023")

ggplot(survey_segs_2, 
       aes(x = start, xend = end, y = type, yend = type, 
           colour = year, group = year)) +
  geom_segment(linewidth = 2, lineend = "round") +
  coord_polar(start = 180) +
  scale_x_date(date_breaks = "1 month",  expand = c(0,0),
               date_labels = "%b",
               limits = as.Date(c("2023-01-01", "2024-12-31"))) +
  scale_color_manual(values = pal) +
  theme(panel.grid.major.y = element_line(linetype = 2)) +
  scale_y_continuous(breaks = c(12, 13, 14), limits = c(5, 14))
```

```{r eval=FALSE}
png(
  here::here("output", "figures", "survey_cal.png"),
  width = 1476,
  height = 1800,
  units = "px",
  type = "cairo"
)
ggplot(survey_segs_2, 
       aes(x = start, xend = end, y = type, yend = type, 
           colour = year, group = year)) +
  geom_segment(linewidth = 5, lineend = "round") +
  coord_polar(start = 180) +
  ylim(5, 15) +
  scale_x_date(date_breaks = "1 month",  expand = c(0,0),
               date_labels = "%b",
               limits = as.Date(c("2023-01-01", "2024-12-31"))) +
  scale_color_manual(values = pal) +
  theme_classic(base_size = 35)
dev.off()
```

Stock hawthorn images from [here](https://stock.adobe.com/images/hawthorn-plant-graphic-black-white-isolated-sketch-illustration-vector/526493884)
